on:
    workflow_call:
        inputs:
            app-version:
                description: 'Application version'
                required: true
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 'Intial Test'
              run: |
                echo "Hello, Alex!"